# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15.1-latest
FROM ghcr.io/daemonless/base:${BASE_VERSION} AS builder

# Install build dependencies
RUN pkg update && \
    pkg install -y \
    FreeBSD-clibs-dev FreeBSD-runtime-dev FreeBSD-libexecinfo-dev \
    FreeBSD-bmake FreeBSD-clang FreeBSD-clang-dev FreeBSD-toolchain \
    FreeBSD-utilities-dev FreeBSD-zlib-dev FreeBSD-audit-dev \
    python314 py314-sqlite3 \
    rust gmake cmake pkgconf \
    libffi webp libxslt libxml2 libjpeg-turbo libheif openjpeg \
    lcms2 freetype2 harfbuzz openldap26-client postgresql17-client openssl libuv \
    node24 npm-node24 yarn-node24 git-lite jq ca_root_nss && \
    pkg clean -ay

# Fetch latest version from GitHub API
RUN MEALIE_VERSION=$(fetch -qo - https://api.github.com/repos/mealie-recipes/mealie/releases/latest | jq -r .tag_name) && \
    echo "MEALIE_VERSION=${MEALIE_VERSION}" > /tmp/mealie_version && \
    echo "Building Mealie ${MEALIE_VERSION}"

ENV CFLAGS="-I/usr/local/include -I/usr/local/include/libxml2" \
    LDFLAGS="-L/usr/local/lib -L/usr/lib -L/lib" \
    LIBRARY_PATH="/usr/lib:/lib:/usr/local/lib" \
    RUSTFLAGS="-C link-arg=-L/usr/lib -C link-arg=-L/lib" \
    CARGO_BUILD_JOBS=2 \
    CARGO_PROFILE_RELEASE_CODEGEN_UNITS=16

# Download Mealie
RUN . /tmp/mealie_version && \
    fetch -qo /tmp/mealie.tar.gz \
    "https://github.com/mealie-recipes/mealie/archive/refs/tags/${MEALIE_VERSION}.tar.gz" && \
    mkdir -p /app && tar -xzf /tmp/mealie.tar.gz -C /app --strip-components=1 && \
    echo "${MEALIE_VERSION}" > /app/version && \
    rm /tmp/mealie.tar.gz

WORKDIR /app

# Build frontend, then clean up node_modules + yarn cache to free disk space
RUN cd /app/frontend && \
    sed -i '' 's/"sass-embedded":.*/"sass": "^1.85.0",/' package.json && \
    sed -i '' 's/"vuetify": "[^"]*"/"vuetify": "4.1.11"/' package.json && \
    yarn install && yarn generate && \
    rm -rf node_modules .yarn /root/.cache/yarn /root/.npm /usr/local/share/.cache

# Mealie 3.28+ requires Python 3.14, and FreeBSD packages py* modules only for
# its default Python (3.12), so pip builds Mealie's pinned dependencies from
# source (orjson, pydantic-core, bcrypt, jiter, watchfiles need Rust). Two are
# handled separately: pillow-heif >= 1.5 needs libheif >= 1.23.1 and FreeBSD
# has 1.22.2, so it is held at 1.4.0 (the FreeBSD port's version), and
# httpx-curl-cffi needs the patched curl_cffi built below. The pgsql extra's
# psycopg2-binary has no FreeBSD wheel, so its pin installs as plain psycopg2.
ARG PILLOW_HEIF_VERSION=1.4.0
RUN python3.14 -m venv /opt/mealie && \
    /opt/mealie/bin/pip install --no-cache-dir --upgrade pip setuptools wheel && \
    /opt/mealie/bin/python -c "import tomllib; p = tomllib.load(open('/app/pyproject.toml', 'rb'))['project']; deps = [d for d in p['dependencies'] if not d.lower().startswith(('pillow-heif', 'httpx-curl-cffi'))]; deps += [d.replace('psycopg2-binary', 'psycopg2') for d in p['optional-dependencies']['pgsql']]; print('\\n'.join(deps))" > /tmp/requirements.txt && \
    cat /tmp/requirements.txt && \
    /opt/mealie/bin/pip install --no-cache-dir -r /tmp/requirements.txt \
      pillow-heif==${PILLOW_HEIF_VERSION} && \
    /opt/mealie/bin/pip install --no-deps --no-cache-dir /app && \
    rm -rf /tmp/requirements.txt /root/.cargo /root/.cache

# curl_cffi (mealie.pkgs.safehttp) publishes no FreeBSD wheel, but upstream does
# ship a FreeBSD libcurl-impersonate, so the sdist builds once the patch adds the
# libs.json row and the libc++ link flag. Version-pinned so an upstream reshuffle
# fails the build instead of silently dropping impersonation.
ARG CURL_CFFI_VERSION=0.16.3
COPY patches/ /tmp/patches/
RUN fetch -qo /tmp/curl_cffi.tar.gz \
      "https://files.pythonhosted.org/packages/source/c/curl_cffi/curl_cffi-${CURL_CFFI_VERSION}.tar.gz" && \
    tar -C /tmp -xzf /tmp/curl_cffi.tar.gz && \
    cd /tmp/curl_cffi-${CURL_CFFI_VERSION} && \
    patch -p1 < /tmp/patches/curl_cffi-${CURL_CFFI_VERSION}-freebsd.patch && \
    /opt/mealie/bin/pip install --no-cache-dir --upgrade cffi setuptools wheel && \
    /opt/mealie/bin/pip install --no-cache-dir --no-build-isolation . && \
    /opt/mealie/bin/pip install --no-cache-dir httpx-curl-cffi==0.1.5 && \
    cd / && rm -rf /tmp/curl_cffi* /tmp/patches

# Download NLTK data
RUN mkdir -p /nltk_data && \
    /opt/mealie/bin/python -c "import nltk; nltk.download('averaged_perceptron_tagger_eng', download_dir='/nltk_data')"

# Production image
ARG BASE_VERSION
FROM ghcr.io/daemonless/base:${BASE_VERSION}
ARG FREEBSD_ARCH=amd64
ARG PACKAGES="python314 py314-sqlite3 libffi webp tiff libxslt libxml2 libxcb libjpeg-turbo libheif libimagequant libavif openjpeg lcms2 freetype2 libraqm harfbuzz openldap26-client postgresql17-client openssl libuv ca_root_nss"
ARG UPSTREAM_URL="https://api.github.com/repos/mealie-recipes/mealie/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:9000/api/app/about"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Mealie" \
      org.opencontainers.image.description="Intuitive self-hosted recipe management app designed to be the best recipe management experience on the web." \
      org.opencontainers.image.source="https://github.com/daemonless/mealie" \
      org.opencontainers.image.url="https://mealie.io/" \
      org.opencontainers.image.documentation="https://docs.mealie.io/" \
      org.opencontainers.image.licenses="AGPL-3.0-only" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Utilities" \
      io.daemonless.port="9000" \
      io.daemonless.volumes="/config" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

RUN pkg update && pkg install -y ${PACKAGES} && \
    pkg clean -ay && rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

COPY --from=builder --chown=bsd:bsd /opt/mealie /opt/mealie
COPY --from=builder --chown=bsd:bsd /nltk_data /nltk_data
COPY --from=builder --chown=bsd:bsd /app/frontend/.output /app/frontend/.output
COPY --from=builder --chown=bsd:bsd /app/mealie /app/mealie
COPY --from=builder --chown=bsd:bsd /app/version /app/version

RUN mkdir -p /config /run/secrets && \
    ln -s /config /app/data && \
    ln -s /app/frontend/.output/public /app/mealie/frontend && \
    chown -R bsd:bsd /app /config /run/secrets

COPY root/ /
RUN chmod +x /etc/services.d/*/run /etc/cont-init.d/* 2>/dev/null || true

ENV MEALIE_HOME="/app" \
    PYTHONPATH=/app \
    NLTK_DATA=/nltk_data \
    VENV_PATH="/opt/mealie" \
    PATH="/opt/mealie/bin:$PATH" \
    PRODUCTION=true \
    TESTING=false \
    APP_PORT=9000

# --- Expose (Injected by Generator) ---
EXPOSE 9000

# --- Volumes (Injected by Generator) ---
VOLUME /config
